# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fun-repo',
                'doc_host': 'https://deven367.github.io',
                'git_url': 'https://github.com/deven367/fun-repo',
                'lib_path': 'fun_repo'},
  'syms': {'fun_repo.core': {'fun_repo.core.foo': ('core.html#foo', 'fun_repo/core.py')}, 'fun_repo.lovely': {}}}
