# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_lovely-tensors.ipynb.

# %% auto 0
__all__ = ['x']

# %% ../nbs/01_lovely-tensors.ipynb 4
import lovely_tensors as lt
import torch

# %% ../nbs/01_lovely-tensors.ipynb 5
lt.monkey_patch()

# %% ../nbs/01_lovely-tensors.ipynb 6
x = torch.randn((3, 100, 100))

# %% ../nbs/01_lovely-tensors.ipynb 7
x

# %% ../nbs/01_lovely-tensors.ipynb 8
x.plt.fig

# %% ../nbs/01_lovely-tensors.ipynb 10
x.chans
